# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4cea8b2d3e66b170c443358b6ef9889b754eb72c58c15e27da767216297e5ee3e5396a890f5356a52b5d0ee9a594ecdb08699b250b03b7f030af8c758a31a73c

test:
  secret_key_base: 11e3ab34d16cfc52ea83b751ba1a2900589c8d7f5260d972af3fe0d102c41488c7e81663f2aaa59097d610aa983bcaae8c2e1f7ca2b1beae6fc4e87b5f514852

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
